### ISSUE TITLE
unknown compression type: CMP_ATTR_UNCOMPRESSED

### ISSUE THREAD

**Issue by nicolas17** [blacktop/go-apfs#2]
Trying to extract small files from an iOS rootfs dmg gives this error:

```
$ apfs cp /data/038-44862-252.dmg /System/Library/FeatureFlags/Domain/Sharing.plist
   ⨯ unknown compression type: CMP_ATTR_UNCOMPRESSED
```
(This dmg is from iPhone_4.7_14.5_18E199_Restore.ipsw but any should work to reproduce the issue)

I speculate that it fails for the exact same set of files that also fail with apfs-fuse (giving "input/output error"), but I haven't done enough testing to be sure.

**Comment by blacktop** [comment]
Interesting! Thank you for letting me know.  It was a somewhat silly mistake, I just wasn't handling the `CMP_ATTR_UNCOMPRESSED` compression type for decmpfs.  That type tells us that the data is not only not compressed, but that it's data is stored in the `APFS_TYPE_XATTR` data.

It should be fixed now. Feel free to close if so.

**Comment by blacktop** [comment]
Oh and by the way if you wanna really see what is going on under the covers try adding the `-V` flag and prepare for a WALL of pretty text. 😉

**Comment by nicolas17** [comment]
This is fixed!
```
   • Created /data/Sharing.plist
```
This already makes go-apfs more useful for me than the apfs-fuse included in blacktop/ipsw.

**Comment by blacktop** [comment]
Nice!! I'm very glad.  Yeah this is going to completely replace `apfs-fuse` in `ipsw` once it's done.  You will them be able to extract files directly out of the IPSW zips with ZERO external dependancies on any operating system! 😎
