### ISSUE TITLE
"Unexpected EOF" error

### ISSUE THREAD

**Issue by nicolas17** [blacktop/go-apfs#3]
When extracting `/System/Library/FeatureFlags/Global.plist` from `iPhone_4.7_14.5_18E199_Restore.ipsw` rootfs (`038-44862-252.dmg`), I get an "unexpected EOF" error:

```
$ apfs cp 038-44862-252.dmg /System/Library/FeatureFlags/Global.plist
   ⨯ unexpected EOF           
```
Running with -V gives confusing log messages, like it was traversing an unrelated directory when the error happened...

**Comment by blacktop** [comment]
I just ran it successfully on `19A5261w__iPhone11,8_iPhone12,1/iOS15b2_018-22754-059.dmg`

Can you tell me what IPSW that dmg came from?

**Comment by nicolas17** [comment]
I'm using [iPhone_4.7_14.5_18E199_Restore.ipsw](https://updates.cdn-apple.com/2021SpringFCS/fullrestores/071-17710/4B2CE1AA-DBBF-47E6-B541-F4E4F745C604/iPhone_4.7_14.5_18E199_Restore.ipsw).

(unrelated, this made me realize I should have been using the `_P3_` ipsws all along since I'm on iPhone 7 :man_facepalming:)

**Comment by blacktop** [comment]
This should be fixed now
